config/routes.rb
Rails.application.routes.draw do
  resources :users, :debentures

  post 'login', to:'users#check', as:'post_login'
  get 'login', to:'users#login', as:'user_login'

  get 'logout', to:'users#log_out', as:'logout'

  get 'info', to:'users#info'

  root 'users#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/debenture.rb
class Debenture < ApplicationRecord
  has_many :passports, class_name: "passport", foreign_key: "passport_1_id"
  has_many :passports, class_name: "passport", foreign_key: "passport_2_id"
end

app/models/passport.rb
class Passport < ApplicationRecord
  belongs_to :debenture, class_name: "passport", optional: true
  belongs_to :debenture, class_name: "passport", optional: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UsersHelper
end

app/controllers/debentures_controller.rb
class DebenturesController < ApplicationController

  def new
    @debenture = User.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login

  end

  def check
    user = User.find_by_username(params[:user][:username])
    if user && params[:user][:password] == user.password
      session_login(user.id)
      redirect_to new_debenture_path
    else
      redirect_to root_path
    end
  end

  def log_out
    log_out_user
    current_user
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(username: params[:user][:username],password: params[:user][:password],email: params[:user][:email])
    @user.save
    redirect_to root_path
  end

  def info

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debentures_helper.rb
module DebenturesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def session_login(user_id)
    session[:id] = user_id
  end

  def current_user
    session[:id]
  end

  def log_out_user
    session[:id] = nil
  end
end

app/views/debentures/new.html.erb
<h3>Создание расписки </h3>
<br>Дата составления расписки:<input type="date"  placeholder="Дата составления расписки"> </br>
<input type="text"  placeholder="Где составлена расписка">
<br><input type="text"  placeholder="Сумма"></br>
<h2>Паспорт получателя денежных средств</h2>
<br><input type="text"  placeholder="Имя"> </br>
<input type="text"  placeholder="Фамилия">
<br><input type="text"  placeholder="Отчество"></br>
<input type="text"  placeholder="Кем выдан">
<br><input type="text"  placeholder="Когда выдан"></br>
<input type="text"  placeholder="Серия">
<br><input type="text"  placeholder="Номер"></br>
 День рождения: <input type="date"  placeholder="День рождения" >
<br><input type="text"  placeholder="Место рождения"></br>
<input type="text"  placeholder="Адрес регистарции">
<br><input type="text"  placeholder="Адрес проживания"></br>
<input type="text"  placeholder="Место рождения">
<br><input type="text"  placeholder="Код подразделения"></br>

<h2>Паспорт передающего денежные средства</h2>
<br><input type="text"  placeholder="Имя"> </br>
<input type="text"  placeholder="Фамилия">
<br><input type="text"  placeholder="Отчество"></br>
<input type="text"  placeholder="Кем выдан">
<br><input type="text"  placeholder="Когда выдан"></br>
<input type="text"  placeholder="Серия">
<br><input type="text"  placeholder="Номер"></br>
День рождения: <input type="date"  placeholder="День рождения" >
<br><input type="text"  placeholder="Место рождения"></br>
<input type="text"  placeholder="Адрес регистарции">
<br><input type="text"  placeholder="Адрес проживания"></br>
<input type="text"  placeholder="Место рождения">
<br><input type="text"  placeholder="Код подразделения"></br>
<button>Отправить</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectDebenture</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if session[:id] != nil %>
      <%=link_to 'Выйти', logout_path  %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/info.html.erb
На этом сайте Вы можете легко заполнить онлайн бланк Расписки в получении денежных средств .

Расписка в получении денежных средств, служит для подтверждении передачи денежных средств от одного человека другому. Обратите внимание, что данная расписка не является документом указывающим на наличие займа. В случае если одно лицо занимает денежные средства другому, необходимо в дополнение к данной расписке заключить договор займа в котором факт передачи или возврата денег документируется распиской в получении денежных средств.

Так же распиской в получении денежных средств можно удостоверять оплату, выдачу, получение, передачу, возврат денег.

app/views/users/login.html.erb
<h3>Авторизация</h3>
<%=link_to 'Регистрация', new_user_path %>
<a href="/info">Информация</a>
<%=form_for :user do |f| %>
  <br><%=f.text_field :username, placeholder:'Логин'%></br>
  <%=f.text_field :password, placeholder:'Пароль' %>
  <br><%=f.submit 'Войти' %></br>
<% end %>

app/views/users/new.html.erb
<h3>Реггистрация</h3>
<%= form_for @user do |f|%>
  <br><%= f.text_field :username, placeholder:'Логин' %></br>
  <%= f.text_field :password, placeholder:'Пароль' %>
  <br><%= f.text_field :email, placeholder:'E-mail' %></br>
  <%= f.submit 'Отправить' %>
<% end %>